SELECT B.name, count(*) TOTALSALES FROM PRODUCTS PR
LEFT JOIN BRANDS B ON B.ID = PR.BRANDID
LEFT JOIN PURCHASEPRODUCT PP ON PP.PRODUCTID = PR.ID
WHERE B.NAME = 'KREATIN' 
GROUP BY B.NAME
ORDER BY TOTALSALES DESC
LIMIT 1


SELECT SUM(PUR.TOTALAMOUNT) FROM PURCHASEPRODUCT PP
LEFT JOIN PRODUCTS PR ON PR.ID = PP.PRODUCTID
LEFT JOIN PURCHASES PUR ON PUR.ID = PP.PURCHASEID
WHERE PR.BRANDID = 4 AND PUR.PURCHASEDATE BETWEEN '2015/01/01' AND '2020-12-31'


SELECT CR.GENDER, COUNT(*) TOTALSALES FROM PURCHASEPRODUCT PP
LEFT JOIN PRODUCTS PR ON PR.ID = PP.PRODUCTID
LEFT JOIN PURCHASES PUR ON PUR.ID = PP.PURCHASEID
LEFT JOIN CUSTOMER CR ON CR.ID = PUR.CUSTOMERID
WHERE PR.NAME = 'L KAMITIN' AND PUR.PURCHASEDATE BETWEEN '2015/01/01' AND '2020/12/31'
GROUP BY CR.GENDER
HAVING count(*)>4
